Repository FRONTENDSCHOOL7/final-12-HoloNyamNyam, pull requests merged in 2023-11, with the labels that each got.

#71 :lipstick:style: 전체적인 css 개선
  src/components/Chat/ChatListItem.jsx
  src/components/Chat/ReceiveMessage.jsx
  src/components/Chat/ReceiveMessageStyle.jsx
  src/components/Feed/FeedItem/StyledFeedItem.jsx
  src/components/Place/PlaceListItemStyle.jsx
  src/components/Profile/InfoProfile.jsx
  src/components/Profile/StyledBtnProfile.jsx
  src/components/Profile/StyledInfoProfile.jsx
  src/components/Profile/StyledRatePlace.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/StyledHeader.jsx
  src/images/search-logo.svg
  src/pages/FollowerList/FollowerList.jsx
  src/pages/FollowerList/FollowerListStyle.jsx
  src/pages/Search/Search.jsx
  src/pages/Splash/SplashStyle.jsx
Labels: :art: HTML/CSS

#72 :sparkles:feat: 맛집수정기능 구현
  src/components/Modal/Modal/Modal.jsx
  src/components/Modal/PlaceCard/PlaceCard.jsx
  src/components/Place/PlaceEdit.jsx
  src/components/Place/PlaceEditStyle.jsx
Labels: :sparkles: 기능 추가, :art: HTML/CSS

#75 :lipstick:style: 팔로워, 냠냠평가 리스트 높이조절
  src/pages/FollowerList/FollowerListStyle.jsx
  src/pages/Place/PlaceList.jsx
  src/pages/Profile/Profile.jsx
Labels: :art: HTML/CSS

#78 :lipstick:style: 앱 밖 배경 css 적용
  public/index.html
  public/style.css
  src/components/Profile/StyledInfoProfile.jsx
  src/components/style/GlobalStyle.jsx
Labels: :art: HTML/CSS

#79 ♻️Refactor: 회원가입 컴포넌트 공통 Input 컴포넌트 적용
  package-lock.json
  src/components/Login/LoginForm.jsx
  src/components/ProfileEdit/ProfileEditForm.jsx
  src/components/ProfileEdit/ProfileEditFormStyle.jsx
  src/components/ProfileSetting/ProfileSettingForm.jsx
  src/components/ProfileSetting/ProfileSettingStyle.jsx
  src/components/Signup/SignUpForm.jsx
  src/components/Signup/SignUpStyle.jsx
  src/components/Signup/StyledSignUp.jsx
  src/components/common/Input/Input.jsx
  src/components/common/Input/StyledInput.jsx
  src/pages/Profile/ProfileEdit.jsx
Labels: :recycle:리팩토링, :art: HTML/CSS

#80 :recycle:refactor: 타사용자, 사용자 모달 다르게 전달, :lipstick:style: 피드백 수용
  src/components/Map/CssPlaceMap.css
  src/components/Modal/Modal/Modal.jsx
  src/components/Modal/PlaceCard/PlaceCard.jsx
  src/components/Place/PlaceListItemStyle.jsx
  src/components/Profile/StyledRatePlace.jsx
  src/components/common/Header/Header.jsx
  src/images/MarkerImageSrc.svg
Labels: :recycle:리팩토링, :art: HTML/CSS

#81 :lipstick:style: 로딩페이지 범위 축소
  src/components/Loading/Loading.jsx
  src/components/Place/PlaceImgPrevStyle.jsx
  src/components/common/Header/Header.jsx
  src/pages/Place/MakePlace.jsx
Labels: :art: HTML/CSS

#84 :bug:fix: 스크롤 끝까지 내린 상태에서 네비 버튼 클릭시 데이터 사라짐 현상 해결
  src/components/Feed/FeedList/FeedList.jsx
  src/components/Map/PlaceMap.jsx
  src/components/Profile/InfoProfile.jsx
Labels: :lady_beetle: 버그 수정

#85 :sparkles:feat: 로그인 페이지 진입 시 자동 포커스
  src/components/common/Input/Input.jsx
Labels: :sparkles: 기능 추가

#86 :sparkles:feat: 냠냠평가 수정 페이지 구현
  src/components/Modal/PlaceCard/PlaceCard.jsx
  src/components/Place/PlaceEdit.jsx
  src/components/Place/PlaceEditStyle.jsx
  src/components/Place/PlaceImgPrev.jsx
  src/components/Place/PlaceImgPrevStyle.jsx
  src/components/Place/StarRating.jsx
  src/components/common/Header/Header.jsx
  src/components/style/GlobalStyle.jsx
  src/pages/Place/EditPlace.jsx
  src/pages/Place/MakePlace.jsx
  src/pages/Place/PlaceStyle.jsx
  src/recoil/placeEditAtom.js
  src/routers/Routers.jsx
Labels: :sparkles: 기능 추가, :lady_beetle: 버그 수정

#90 ✨💄: 피드백 반영
  src/components/Feed/FeedItem/FeedItem.jsx
  src/components/Feed/FeedItem/StyledFeedItem.jsx
  src/components/Feed/FeedList/StyledFeedList.jsx
  src/components/Modal/PlaceCard/PlaceCard.jsx
  src/components/Modal/PlaceCard/PlaceCardStyle.jsx
  src/components/Profile/RatePlace.jsx
  src/components/common/Button/Button.jsx
  src/components/common/Nav/Nav.jsx
  src/components/common/Nav/StyledNav.jsx
  src/images/SpriteIcon.svg
  src/images/Star.svg
  src/images/button-logo-white.svg
  src/images/button-logo.png
  src/images/close-btn.svg
  src/images/navigationIcon.svg
  src/images/sprite-nav.svg
  src/pages/Search/Search.jsx
  src/pages/Welcome/WelcomeStyle.jsx
Labels: :sparkles: 기능 추가, :art: HTML/CSS

#93 :sparkles:feat: 채팅 페이지 개선
  src/components/Chat/ChatListItem.jsx
  src/components/Chat/ReceiveMessage.jsx
  src/components/Chat/ReceiveMessageStyle.jsx
  src/components/Chat/SendMessage.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/StyledHeader.jsx
  src/components/common/Nav/ChatNav.jsx
  src/components/common/Nav/ChatNavStyle.jsx
  src/images/chatMembers/holo_dev.png
  src/images/chatMembers/holo_doggo.jpg
  src/images/chatMembers/holo_dori.jpg
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatRoom.jsx
  src/recoil/chatAtom.js
Labels: :art: HTML/CSS

#95 :sparkles:feat: 게시글 삭제되면 프로필에 곧바로 새로 반영
  src/components/Modal/Alert/Alert.jsx
Labels: :sparkles: 기능 추가

#96 :sparkles:feat: 타사용자에서 바로 프로필 넘어가면 해당 데이터 불러오도록 변경
  src/components/Feed/FeedList/FeedList.jsx
Labels: :art: HTML/CSS

#99 :bug:fix: 채팅방 데이터 넘김 오류 해결
  src/components/Chat/ChatListItem.jsx
  src/components/Profile/BtnProfile.jsx
  src/components/common/Header/Header.jsx
Labels: :lady_beetle: 버그 수정

#101 :lipstick:style: 파비콘 설정
  public/favicon.ico
  public/index.html
Labels: :art: HTML/CSS

#102 :sparkles:feat: 카카오API를 이용한 공유하기 기능 추가
  public/index.html
  src/components/Modal/Alert/Alert.jsx
  src/components/Modal/Modal/Modal.jsx
  src/components/Place/PlaceListItemStyle.jsx
  src/components/Profile/BtnProfile.jsx
  src/components/Profile/InfoProfile.jsx
  src/components/Profile/RatePlace.jsx
  src/components/Profile/StyledRatePlace.jsx
  src/pages/Place/PlaceList.jsx
  src/recoil/userInfoAtom.js
Labels: :sparkles: 기능 추가

#104 :recycle:refactor: 브라우저 종료시 스토리지 삭제
  src/components/Comment/Comment.jsx
  src/components/Feed/FeedComment/FeedComment.jsx
  src/components/Feed/FeedCreate/FeedCreate.jsx
  src/components/Feed/FeedHome/FeedHome.jsx
  src/components/Feed/FeedItem/FeedItem.jsx
  src/components/Feed/FeedList/FeedList.jsx
  src/components/FollowItem/FollowItem.jsx
  src/components/Login/LoginForm.jsx
  src/components/Modal/Alert/Alert.jsx
  src/components/Modal/PlaceCard/PlaceCard.jsx
  src/components/Place/PlaceListItem.jsx
  src/components/Profile/BtnProfile.jsx
  src/components/Profile/InfoProfile.jsx
  src/components/Profile/RatePlace.jsx
  src/components/ProfileEdit/ProfileEditForm.jsx
  src/components/Search/SearchList.jsx
  src/components/common/Header/Header.jsx
  src/pages/FollowerList/FollowerList.jsx
  src/pages/Place/EditPlace.jsx
  src/pages/Place/MakePlace.jsx
  src/pages/Place/PlaceList.jsx
  src/pages/Profile/ProfileEdit.jsx
  src/pages/Splash/Splash.jsx
Labels: :recycle:리팩토링

#107 :recycle:refactor: 브라우저 종료시 스토리지 삭제 코드 추가
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Feed/FeedDetail.jsx
  src/pages/Feed/FeedUpload.jsx
  src/pages/FollowerList/FollowerList.jsx
  src/pages/Home/Home.jsx
  src/pages/Place/EditPlace.jsx
  src/pages/Place/MakePlace.jsx
  src/pages/Place/Map.jsx
  src/pages/Place/PlaceList.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileEdit.jsx
  src/pages/ProfileSetting/ProfileSetting.jsx
  src/pages/Search/Search.jsx
Labels: :recycle:리팩토링

#116 :bug:fix: 프로필에서 제일 하단 게시글 삭제하면 게시글 날라감 현상 해결
  src/components/Feed/FeedList/FeedList.jsx
Labels: :lady_beetle: 버그 수정

#119 :bug:fix: 냠냠평가 인풋 새로고침 막음
  src/pages/Place/EditPlace.jsx
  src/pages/Place/MakePlace.jsx
Labels: :lady_beetle: 버그 수정

#123 :bug:fix: 엄격모드 해제 시 무한로딩 오류 해결 코드 추가
  src/components/Feed/FeedList/FeedList.jsx
Labels: :recycle:리팩토링, :lady_beetle: 버그 수정

#125 :recycle:refactor: feedList 코드 리펙토링
  src/components/Feed/FeedList/FeedList.jsx
Labels: :recycle:리팩토링

#128 :bug:fix: :lipstick:style: 스토리지 수정 및 댓글 css 수정
  src/components/Comment/Comment.jsx
  src/components/Feed/FeedComment/FeedComment.jsx
  src/components/Feed/FeedComment/StyledFeedComment.jsx
Labels: :art: HTML/CSS, :lady_beetle: 버그 수정

#133 :bug:fix: 팔로우팔로잉 리스트 로딩 컴포넌트 안보이는 이슈
  src/pages/FollowerList/FollowerList.jsx
Labels: :lady_beetle: 버그 수정

#136 :recycle:refactor: recoil 저장소 위치 바꿈
  src/components/Modal/Alert/Alert.jsx
  src/recoil/cardShowAtom.js
  src/recoil/chatAtom.js
  src/recoil/feedEditAtom.js
  src/recoil/modalAtom.js
  src/recoil/placeEditAtom.js
  src/recoil/userInfoAtom.js
  src/recoil/viewBtnAtom.js
Labels: :recycle:리팩토링

#138 :recycle:refactor: 프로필 사진 엑박 해결과 디폴트 이미지 넣기
  src/components/ProfileEdit/ProfileEditForm.jsx
  src/components/ProfileSetting/ProfileSettingForm.jsx
Labels: :recycle:리팩토링, :lady_beetle: 버그 수정

#139 :recycle:refactor: 리코일 스토리지 경로 수정
  src/recoil/skeletonAtom.js
Labels: :recycle:리팩토링

#140 :recycle:refactor: 모달창 불러올때 모달창에서만 스켈레톤 불러오기
  src/components/Feed/FeedHome/FeedHome.jsx
  src/components/Modal/PlaceCard/PlaceCard.jsx
  src/components/Profile/InfoProfile.jsx
  src/components/Profile/RatePlace.jsx
Labels: :recycle:리팩토링

#142 :bug:fix: 포스트 개수 10이상 안불러와짐 문제 해결
  src/api/feed.js
  src/components/Profile/InfoProfile.jsx
Labels: :lady_beetle: 버그 수정

#145 :bug:fix: 냠냠평가 이미지 파일 업로드 취소시 에러 해결
  src/components/Place/PlaceImgPrev.jsx
Labels: :lady_beetle: 버그 수정

#149 :recycle:refactor: 테스트 계정 맛보기 기능 구현
  src/components/Login/LoginForm.jsx
Labels: :recycle:리팩토링

#152 :lipstick:style: 툴팁 추가
  src/components/Carousels/Carousel.jsx
  src/components/Feed/FeedCreate/FeedCreate.jsx
  src/components/Feed/FeedItem/FeedItem.jsx
  src/components/Place/PlaceImgPrev.jsx
  src/components/Profile/BtnProfile.jsx
  src/components/ProfileEdit/ProfileEditForm.jsx
  src/components/ProfileSetting/ProfileSettingForm.jsx
  src/components/Signup/SignUpForm.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Nav/ChatNav.jsx
  src/components/common/Nav/ChatNavStyle.jsx
  src/components/common/Nav/Nav.jsx
  src/pages/Place/MakePlace.jsx
Labels: :art: HTML/CSS

#154 :bug:fix: 회원가입 절차대로 진행하도록 유도
  src/components/ProfileSetting/ProfileSettingForm.jsx
  src/components/Signup/SignUpForm.jsx
  src/pages/ProfileSetting/ProfileSetting.jsx
  src/pages/SignUp/SignUpSuccess.jsx
  src/recoil/signUpAtom.js
Labels: :lady_beetle: 버그 수정
