Repository FRONTENDSCHOOL7/final-12-HoloNyamNyam, pull requests merged in 2023-10, with the labels that each got.

#11 ✨Feat: nav 컴포넌트 구현
  package-lock.json
  src/App.js
  src/components/common/Nav/Nav.jsx
  src/components/common/Nav/StyledNav.jsx
  src/images/arrow_top.svg
  src/images/navigationIcon.svg
Labels: :sparkles: 기능 추가, :art: HTML/CSS

#12 :sparkles:feat: 라우터 연결 추가, 필요 page파일 생성
  src/App.js
  src/index.js
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Login/Login.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpSuccess.jsx
  src/routers/Routers.jsx
Labels: :sparkles: 기능 추가

#13 :sparkles:feat: nav 라우터 연결
  src/components/common/Nav/Nav.jsx
  src/components/common/Nav/StyledNav.jsx
  src/images/navigationIcon.svg
Labels: :sparkles: 기능 추가

#24 ✨feat: chat list 페이지 구현, chat 컴포넌트 구현
  src/components/Chat/ChatListItem.jsx
  src/components/Chat/ChatListItemStyle.jsx
  src/images/user_profile.png
  src/pages/Chat/ChatList.jsx
  src/pages/SignUp/SignUpSuccess.jsx
  src/pages/Splash/Splash.jsx
  src/pages/Welcome/WelcomeStyle.jsx
Labels: :sparkles: 기능 추가, :art: HTML/CSS

#32 ✨feat: chat 페이지 구현
  src/components/Chat/ChatListItemStyle.jsx
  src/components/Chat/ReceiveMessage.jsx
  src/components/Chat/ReceiveMessageStyle.jsx
  src/components/Chat/SendMessage.jsx
  src/components/Modal/Modal/Modal.jsx
  src/components/common/Nav/ChatNav.jsx
  src/components/common/Nav/ChatNavStyle.jsx
  src/images/img-button.png
  src/pages/Chat/ChatRoom.jsx
Labels: :sparkles: 기능 추가, :art: HTML/CSS

#33 ✨feat: modal 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Modal/Alert/Alert.jsx
  src/components/Modal/Alert/AlertStyle.jsx
  src/components/Modal/Modal/Modal.jsx
  src/components/Modal/Modal/ModalStyle.jsx
  src/components/common/Header/Header.jsx
  src/pages/Chat/ChatRoom.jsx
  src/recoil/modalAtom.js
Labels: :sparkles: 기능 추가, :art: HTML/CSS

#39 ✨feat: search 기능 구현
  src/api/search.js
  src/components/Search/SearchList.jsx
  src/components/Search/SearchListStyle.jsx
  src/pages/Search/Search.jsx
Labels: :sparkles: 기능 추가

#40 💄style: scroll top 버튼 스타일 변경
  src/components/Modal/Modal/Modal.jsx
  src/components/common/Nav/StyledNav.jsx
  src/images/arrow_top.svg
Labels: :art: HTML/CSS

#46 :sparkles:feat: 맛집평가 페이지 구현
  src/api/recommend.js
  src/components/Modal/RecommendCard/RecommendCard.jsx
  src/components/Modal/RecommendCard/RecommendCardStyle.jsx
  src/components/Place/PlaceListItem.jsx
  src/components/Place/PlaceListItemStyle.jsx
  src/images/SpriteIcon.svg
  src/images/Star.svg
  src/images/close.svg
  src/pages/Place/PlaceList.jsx
  src/pages/Welcome/WelcomeStyle.jsx
  src/recoil/cardShowAtom.js
Labels: :sparkles: 기능 추가, :art: HTML/CSS

#51 🚚rename: placeWrap위치변경, min-width 변경
  src/components/Modal/PlaceCard/PlaceCard.jsx
  src/components/Place/PlaceListItem.jsx
  src/components/Place/PlaceListItemStyle.jsx
  src/pages/Place/PlaceList.jsx
Labels: :recycle:리팩토링

#56 :sparkles:feat: 팔로잉, 팔로우 리스트 페이지 구현
  src/api/follow.js
  src/components/FollowItem/FollowItem.jsx
  src/components/FollowItem/FollowItemStyle.jsx
  src/components/Modal/PlaceCard/PlaceCard.jsx
  src/components/Profile/RatePlace.jsx
  src/components/common/Button/Button.jsx
  src/pages/FollowerList/FollowerList.jsx
  src/pages/FollowerList/FollowerListStyle.jsx
Labels: :sparkles: 기능 추가, :art: HTML/CSS

#68 ✨feat: 맛집평가 등록 페이지 구현
  package-lock.json
  package.json
  public/index.html
  src/components/Modal/Modal/ModalStyle.jsx
  src/components/Modal/PlaceCard/PlaceCard.jsx
  src/components/Modal/PlaceCard/PlaceCardStyle.jsx
  src/components/Place/PlaceImgPrev.jsx
  src/components/Place/PlaceImgPrevStyle.jsx
  src/components/Place/StarRating.jsx
  src/components/common/Header/Header.jsx
  src/pages/FollowerList/FollowerList.jsx
  src/pages/Place/MakePlace.jsx
Labels: :sparkles: 기능 추가, :art: HTML/CSS
